const KR=[
['KR','삼성전자','005930.KS'],['KR','SK하이닉스','000660.KS'],['KR','현대차','005380.KS'],['KR','기아','000270.KS'],['KR','NAVER','035420.KS'],['KR','카카오','035720.KS'],['KR','LG에너지솔루션','373220.KS'],['KR','삼성바이오로직스','207940.KS'],['KR','셀트리온','068270.KS'],['KR','POSCO홀딩스','005490.KS'],['KR','KB금융','105560.KS'],['KR','신한지주','055550.KS'],['KR','하나금융지주','086790.KS'],['KR','우리금융지주','316140.KS'],['KR','삼성SDI','006400.KS'],['KR','LG화학','051910.KS'],['KR','현대모비스','012330.KS'],['KR','삼성물산','028260.KS'],['KR','SK이노베이션','096770.KS'],['KR','SK스퀘어','402340.KS'],['KR','KT','030200.KS'],['KR','SK텔레콤','017670.KS'],['KR','LG유플러스','032640.KS'],['KR','한국전력','015760.KS'],['KR','HD현대중공업','329180.KS'],['KR','HD한국조선해양','009540.KS'],['KR','한화오션','042660.KS'],['KR','두산에너빌리티','034020.KS'],['KR','두산밥캣','241560.KS'],['KR','한화에어로스페이스','012450.KS'],['KR','현대건설','000720.KS'],['KR','HMM','011200.KS'],['KR','대한항공','003490.KS'],['KR','아모레퍼시픽','090430.KS'],['KR','LG전자','066570.KS'],['KR','삼성전기','009150.KS'],['KR','삼성중공업','010140.KS'],['KR','에코프로비엠','247540.KQ'],['KR','에코프로','086520.KQ'],['KR','HLB','028300.KQ'],['KR','알테오젠','196170.KQ'],['KR','펄어비스','263750.KQ'],['KR','카카오게임즈','293490.KQ'],['KR','JYP Ent.','035900.KQ'],['KR','에스엠','041510.KQ'],['KR','리노공업','058470.KQ'],['KR','클래시스','214150.KQ'],['KR','레인보우로보틱스','277810.KQ'],['KR','두산로보틱스','454910.KS'],['KR','LS ELECTRIC','010120.KS']
];
const US=[
['US','Apple','AAPL'],['US','NVIDIA','NVDA'],['US','Microsoft','MSFT'],['US','Amazon','AMZN'],['US','Alphabet','GOOGL'],['US','Meta','META'],['US','Tesla','TSLA'],['US','Broadcom','AVGO'],['US','AMD','AMD'],['US','Netflix','NFLX'],['US','JPMorgan','JPM'],['US','Palantir','PLTR'],['US','Coca-Cola','KO'],['US','Walmart','WMT'],['US','Costco','COST'],['US','Berkshire Hathaway','BRK-B'],['US','Eli Lilly','LLY'],['US','Visa','V'],['US','Mastercard','MA'],['US','Exxon Mobil','XOM'],['US','Chevron','CVX'],['US','Johnson & Johnson','JNJ'],['US','Procter & Gamble','PG'],['US','Oracle','ORCL'],['US','Salesforce','CRM'],['US','Adobe','ADBE'],['US','ServiceNow','NOW'],['US','Cisco','CSCO'],['US','Intel','INTC'],['US','Qualcomm','QCOM'],['US','Micron','MU'],['US','Applied Materials','AMAT'],['US','Texas Instruments','TXN'],['US','Arm Holdings','ARM'],['US','Super Micro Computer','SMCI'],['US','Uber','UBER'],['US','Airbnb','ABNB'],['US','Shopify','SHOP'],['US','Snowflake','SNOW'],['US','Coinbase','COIN'],['US','Robinhood','HOOD'],['US','Mara Holdings','MARA'],['US','SoFi','SOFI'],['US','Rivian','RIVN'],['US','Ford','F'],['US','General Motors','GM'],['US','Boeing','BA'],['US','Caterpillar','CAT'],['US','McDonald’s','MCD'],['US','Nike','NKE']
];
const universe=[...KR,...US];
function ema(a,n){const k=2/(n+1);let e=a[0];return a.map((v,i)=>i?(e=(v-e)*k+e):e)}
function sma(a,n){if(a.length<n)return null;return a.slice(-n).reduce((x,y)=>x+y,0)/n}
function rsi(a,n=14){let g=0,l=0,o=Array(a.length).fill(null);for(let i=1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n;if(i>=n)o[i]=l===0?100:100-100/(1+g/l)}return o}
function macd(a){const e12=ema(a,12),e26=ema(a,26),m=e12.map((x,i)=>x-e26[i]),s=ema(m,9);return {m,s,h:m.map((x,i)=>x-s[i])}}
function atr(h,l,c,n=14){const tr=c.map((x,i)=>i?Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])):h[i]-l[i]);return sma(tr,n)}
function pivots(c,r=4){const lows=[],highs=[];for(let i=r;i<c.length-r;i++){let lo=true,hi=true;for(let j=1;j<=r;j++){lo&&=(c[i]<c[i-j]&&c[i]<=c[i+j]);hi&&=(c[i]>c[i-j]&&c[i]>=c[i+j])}if(lo)lows.push(c[i]);if(hi)highs.push(c[i])}return {support:lows.at(-1)??sma(c,20)*.95,resistance:highs.at(-1)??sma(c,20)*1.05}}
function divergence(c,rv){const pts=[];for(let i=2;i<rv.length-2;i++)if(rv[i]!=null&&rv[i]>=rv[i-1]&&rv[i]>rv[i+1])pts.push(i);const a=pts.at(-2),b=pts.at(-1);if(a==null||b==null)return {bull:false,bear:false};return {bull:c[b]<c[a]&&rv[b]>rv[a],bear:c[b]>c[a]&&rv[b]<rv[a]}}
async function quote(sym){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=1y&interval=1d`;const res=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store'});if(!res.ok)throw Error(`data ${res.status}`);const q=(await res.json()).chart.result?.[0];if(!q)throw Error('no data');const z=q.indicators.quote[0];const rows=z.close.map((c,i)=>({c:Number(c),h:Number(z.high[i]),l:Number(z.low[i]),v:Number(z.volume[i])})).filter(x=>Number.isFinite(x.c)&&x.c>0);return {c:rows.map(x=>x.c),h:rows.map(x=>x.h),l:rows.map(x=>x.l),v:rows.map(x=>x.v)}}
function analyze(meta,d){const {c,h,l,v}=d,i=c.length-1,p=c[i],rv=rsi(c),M=macd(c),R=rv[i]??50,ma20=sma(c,20),ma50=sma(c,50),ma200=sma(c,200),vol=sma(v,20),vr=vol?v[i]/vol:1,{support,resistance}=pivots(c),div=divergence(c,rv),a=atr(h,l,c);let score=0,why=[],risk=[];
if(p>ma20){score+=8;why.push('20일선 위')}else risk.push('단기 추세 약함');if(p>ma50){score+=10;why.push('50일선 위')}else risk.push('50일선 아래');if(ma200&&p>ma200){score+=10;why.push('200일선 위')}else risk.push('장기 추세 확인 필요');if(M.m[i]>M.s[i]){score+=12;why.push('MACD 상승')}else risk.push('MACD 약세');if(M.h[i]>0){score+=7;why.push('MACD 히스토그램 양수')}if(R>=45&&R<=68){score+=10;why.push('RSI 과열 전 구간')}if(R<35){score+=7;why.push('RSI 과매도 반등 후보')}if(R>75){score-=8;risk.push('RSI 과열')}if(div.bull){score+=15;why.push('RSI 상승 다이버전스')}if(div.bear){score-=12;risk.push('RSI 하락 다이버전스')}if(vr>=1.5){score+=10;why.push('거래량 1.5배 이상')}else if(vr>=1.1){score+=5;why.push('평균 이상 거래량')}else risk.push('거래량 확인 필요');if(support&&p>support&&((p-support)/p)<.08){score+=7;why.push('지지선 인접')}if(resistance&&resistance>p&&((resistance-p)/p)>.04){score+=6;why.push('저항선까지 여유')}const change=(p/c[i-1]-1)*100,trend=p>ma20&&ma20>ma50?'상승':p<ma20&&ma20<ma50?'하락':'혼조';score=Math.max(0,Math.min(100,Math.round(score)));let status=score>=80?'강한 상승 후보':score>=70?'상승 추세 후보':score>=60?'반등 후보':'관망';const entry=p,stop=Math.max(0,support?Math.min(support,p-a*1.2):p-a*1.5),target=resistance&&resistance>p?resistance:p+a*2.5,rr=target>entry&&stop<entry?(target-entry)/(entry-stop):null;return {market:meta[0],name:meta[1],symbol:meta[2],price:p,change,rsi:R,macd:M.m[i],signal:M.s[i],hist:M.h[i],ma20,ma50,ma200,volumeRatio:vr,atr:a,support,resistance,bullDiv:div.bull,bearDiv:div.bear,trend,score,status,why,risk,entry,stop,target,rr:rr&&Number.isFinite(rr)?rr:null,last20:c.slice(-20),last60:c.slice(-60)}}
async function scan(){const out=[];for(const m of universe){try{out.push(analyze(m,await quote(m[2])))}catch(e){console.error(m[2],e.message)}}out.sort((a,b)=>b.score-a.score);return {updatedAt:new Date().toISOString(),universeSize:universe.length,successCount:out.length,failedCount:universe.length-out.length,top10:out.slice(0,10),all:out}}
module.exports={scan,universe};
